
<iframe width="<?php echo $block->getData('widgetwidth'); ?>" height="<?php echo $block->getData('widgetheight'); ?>" src="<?php echo $block->getData('widgetshortcode'); ?>" title="YouTube video player" 
frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
 allowfullscreen></iframe>

 
 <?php // https://www.youtube.com/embed/EAytFJWWzSE ?>